### ISSUE TITLE
Which version of nodejs should I use in Ubuntu?

### ISSUE THREAD

**Issue by Xuanwo** [kevin-roark/socket.io-computer#11]
Hello, everyone~
I'm trying to buld a socket.io-computer in ubtuntu 15.10, but I meet error in nodejs 0.8 & 0.10.
I can see the pages works well ,but I can't run the qemu because the package canvas can't be installed.

log are like that:

## in node.js 0.10
```
./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while tryin to load binding.gyp
ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/v0.10.39/lib/node_moduls/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:82012)
gyp ERR! System Linux 3.19.0-20-generic
gyp ERR! command "node" "/root/.nvm/v0.10.39/lib/node_modules/npm/node_modules/ode-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/socket.io-computer/node_modules/canvas
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> utf-8-validate@1.1.0 install /root/socket.io-computer/node_modules/socket.io/ode_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/root/socket.io-computer/node_modules/socket.io/node_odules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/root/socket.io-computer/node_modules/socket.io/node_mdules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'

> utf-8-validate@1.0.1 install /root/socket.io-computer/node_modules/socket.io-lient/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/root/socket.io-computer/node_modules/socket.io-clien/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/buil'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/root/socket.io-computer/node_modules/socket.io-clientnode_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.3","npm":"1.4.28"})

> bufferutil@1.1.0 install /root/socket.io-computer/node_modules/socket.io/nodemodules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/root/socket.io-computer/node_modules/socket.io/node_odules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/root/socket.io-computer/node_modules/socket.io/node_mdules/engine.io/node_modules/ws/node_modules/bufferutil/build'
\
> jpeg@1.0.3 install /root/socket.io-computer/node_modules/jpeg
> node-gyp configure build

make: Entering directory '/root/socket.io-computer/node_modules/jpeg/build'
  CXX(target) Release/obj.target/jpeg/src/common.o
  CXX(target) Release/obj.target/jpeg/src/jpeg_encoder.o
In file included from ../src/jpeg_encoder.cpp:1:0:
../src/jpeg_encoder.h:6:21: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
                     ^
compilation terminated.
jpeg.target.mk:86: recipe for target 'Release/obj.target/jpeg/src/jpeg_encoder.' failed
make: *** [Release/obj.target/jpeg/src/jpeg_encoder.o] Error 1
make: Leaving directory '/root/socket.io-computer/node_modules/jpeg/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.39/lib/node_modulesnpm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:82012)
gyp ERR! System Linux 3.19.0-20-generic
gyp ERR! command "node" "/root/.nvm/v0.10.39/lib/node_modules/npm/node_modules/ode-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /root/socket.io-computer/node_modules/jpeg
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.39,"npm":"1.4.28"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.39,"npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.0.39","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.39,"npm":"1.4.28"})

> bufferutil@1.0.1 install /root/socket.io-computer/node_modules/socket.io-cliet/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/root/socket.io-computer/node_modules/socket.io-clien/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/root/socket.io-computer/node_modules/socket.io-clientnode_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-20-generic
npm ERR! command "/root/.nvm/v0.10.39/bin/node" "/root/.nvm/v0.10.39/bin/npm" "nstall"
npm ERR! cwd /root/socket.io-computer
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

## in nodejs 0.8
```
npm ERR! Error: No compatible version found: debug@'^0.8.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3","2.2.0"]
npm ERR!     at installTargetsError (/root/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /root/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/root/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-20-generic
npm ERR! command "/root/.nvm/v0.8.28/bin/node" "/root/.nvm/v0.8.28/bin/npm" "instal"
npm ERR! cwd /root/socket.io-computer
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
```

And with

```
npm WARN package.json queue3@1.0.2 No repository field.
```

**Comment by computernewb** [comment]
Canvas appears to be the reason for the failure. Canvas builds from the "node" folder however in Debian-based distributions node is renamed nodejs in order to avoid a conflict with a dependency that also happens to be called "node".

I fixed it by running the following commands:

Installing 'nodejs-legacy'; sudo apt-get -y install nodejs-legacy
Then creating a symlink; sudo ln -s /usr/bin/nodejs /usr/sbin/node

Finally, installing all of its dependencies by running sudo apt-get -y install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

Try running those commands, then try building again.

**Comment by Xuanwo** [comment]
I'll have a try, thanks a lot!

**Comment by kevin-roark** [comment]
Hi! If you want, feel free to submit a PR adding these instructions to the
README; seems like a decent number of people have run into the issue and
maybe your experience would help :)

**Comment by Xuanwo** [comment]
I will

**Comment by Xuanwo** [comment]
npm install success!
But I meet this while I run emu-runner.js

```
/root/socket.io-computer/vnc.js:68
    this.state.push(rgb, 0, 0, rect.width, rect.height);
               ^
Error: Pushed fragment exceeds FixedJpegStack's width.
    at VNC.drawRect (/root/socket.io-computer/vnc.js:68:16)
    at RfbClient.EventEmitter.emit (events.js:95:17)
    at ReadFixedRequest.callback (/root/socket.io-computer/node_modules/rfb2/rfbclient.js:507:13)
    at ReadFixedRequest.execute (/root/socket.io-computer/node_modules/rfb2/unpackstream.js:80:14)
    at UnpackStream.resume (/root/socket.io-computer/node_modules/rfb2/unpackstream.js:271:30)
    at UnpackStream.write (/root/socket.io-computer/node_modules/rfb2/unpackstream.js:199:10)
    at Socket.<anonymous> (/root/socket.io-computer/node_modules/rfb2/rfbclient.js:25:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
THE EMULATOR DIED
```

**Comment by Xuanwo** [comment]
Wowwwwwwwww!

I change the width&height to 1024*768, and I made it!
I will write something to make it easier for new one to build it.

Thanks for all~

**Comment by computernewb** [comment]
No problem. If you want to remove that laptop image and not make your users have to zoom in, I can also provide the CSS code for you.

**Comment by Xuanwo** [comment]
I modify the css by myself, and I need more test.
If I'm ready, I will paste it here.

And, thank you a lot, without your help, I will waste more time in it.
