### ISSUE TITLE
Cannot find module 'browserify-middleware' on my mac air

### ISSUE THREAD

**Issue by yanshuai** [kevin-roark/socket.io-computer#3]
I have executed `npm install -g  browserify-middleware`, but when I execute node app.js, it had errors as follows:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'browserify-middleware'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/yanshuai/Downloads/socket.io-computer/app.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

How can I fix it?

**Comment by iamajeesh** [comment]
just run

npm install

in the project folder.
